version: '3'
services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    environment:
      - DBNAME=bottlecrm
      - DBUSER=crm          # Ensure it matches the .env
      - DBPASSWORD=crm      # Ensure it matches the .env
      - DBHOST=crm-db       # Correctly points to the DB service
      - DBPORT=5432
      
    depends_on:
      - crm-db
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - nw

    
  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=bottlecrm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm -d bottlecrm"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nw

networks:
  nw: {}
